### PR TITLE
COV-7: setup `Dockerfile` for web server and docker-compose

### PR DESCRIPTION
**Pull request by jason-gerard**
JIRA: https://soen-390-covid-tracker.atlassian.net/browse/COV-7

## Context
We want to use docker in production and in our local development environments. This pr adds the required files, configuration, and documentation to do that.

## Changes
- Added `Dockerfile` in server root
- Added `docker-compose.yml` in project root
- Added `.env` file and library to extract out environment specific project configuration
- Added documentation for how to start and run project using docker and docker-compose

### CODE REVIEW

**Review by Andre-Ibrahim — APPROVED** [review]
looks good

**Comment by domsec** [comment]
Lets not merge this until the Windows instructions are completed.

**Comment by jason-gerard** [comment]
> Lets not merge this until the Windows instructions are completed.

I'd prefer to just merge it and have someone write the windows instructions in a different pr since I don't have windows and I it's usually best practice to have 1 contributor per pull request.

**Comment by domsec** [comment]
> > Lets not merge this until the Windows instructions are completed.
> 
> I'd prefer to just merge it and have someone write the windows instructions in a different pr since I don't have windows and I it's usually best practice to have 1 contributor per pull request.

Fair enough. Assign the ticket to me (if there already is one) and I'll take care of the Windows side.

**Review by domsec — APPROVED** [review]

**Comment by jason-gerard** [comment]
> > > Lets not merge this until the Windows instructions are completed.
> > 
> > 
> > I'd prefer to just merge it and have someone write the windows instructions in a different pr since I don't have windows and I it's usually best practice to have 1 contributor per pull request.
> 
> Fair enough. Assign the ticket to me (if there already is one) and I'll take care of the Windows side.

Ticket is here, https://soen-390-covid-tracker.atlassian.net/browse/COV-71, it is a sub-task of the larger task https://soen-390-covid-tracker.atlassian.net/browse/COV-7

I assigned it to you

**Pull request merged**
