### PR TITLE
COV-3: setup basic web server

### PR DESCRIPTION
**Pull request by jason-gerard**
JIRA: https://soen-390-covid-tracker.atlassian.net/browse/COV-3

### CODE REVIEW

**Comment by domsec** [comment]
Looks good. 

Just a reminder we'll need to update the README with a Getting Started (Prerequisites, Setup, etc.) section. Maybe include it in this PR if it is not already planned in a future PR.

**Review by domsec — COMMENTED** [review]
Looks good. 

Just a reminder we'll need to update the README with a Getting Started (Prerequisites, Setup, etc.) section. Maybe include it in this PR if it is not already planned in a future PR.

**Comment by jason-gerard** [comment]
> Looks good.
> 
> Just a reminder we'll need to update the README with a Getting Started (Prerequisites, Setup, etc.) section. Maybe include it in this PR if it is not already planned in a future PR.

We are going to be using docker (done in another pr) but I'll add a section for doing it outside of docker

**Review by Kastor14 — APPROVED** [review]

**Comment by domsec** [comment]
> > Looks good.
> > Just a reminder we'll need to update the README with a Getting Started (Prerequisites, Setup, etc.) section. Maybe include it in this PR if it is not already planned in a future PR.
> 
> We are going to be using docker (done in another pr) but I'll add a section for doing it outside of docker

Okie dokie. Since we'll be using Docker, we'll just add the section to cover setting up the Docker environment. No need for the section to also cover how to run the app outside of Docker.

**Review by domsec — APPROVED** [review]

**Pull request merged**
